### PR TITLE
Hackernews

### LINKED ISSUE #12: Site: Add hackernews functionality
see title

### PR DESCRIPTION
**Pull request by ginglis13**
# Description

Work in progress Hackernews additions. Includes index frame, story frame (subreddit equivalent), and thread frame functionality. I more or less followed the structure for Reddit functionality, with differences being mainly in that HN's API is not quite on the same level as Reddit's. The thread frame needs to be fleshed out, but there are complications per discussion in #12 . Feel free to clone this branch to check out what's working, and more importantly, what's not working. 

**We should also probably change the target branch of this PR before any merging**. Don't wanna bork master.

Fixes #12 

## Type of change

Please delete options that are not relevant.

- [X] New feature (non-breaking change which adds functionality)
- [X] This change requires a documentation update

# Checklist:

- [X] My code follows the style of this project
- [X] I have performed a self-review of my own code
- [X] My code is self documenting
- [X] My changes generate no new major crashes/bugs

### CODE REVIEW

**Comment by sambattalio** [comment]
Love to see it :rocket:

**Comment by ginglis13** [comment]
I think I have found a solution: A different API provided by Algolia does a much better job when returning info about a post. My approach will be to keep the existing code in place with the official HN API and to use this API for posts only. Here is an [example response](https://hn.algolia.com/api/v1/items/20679387) for [this HN article](https://news.ycombinator.com/item?id=20679387). As you can see, both APIs use the article's unique ID as the method for requesting the article's data. For contrast, here is the [HN official API response](a story: https://hacker-news.firebaseio.com/v0/item/8863.json?print=pretty) for the same post.

This newly discovered API is by no means lightning fast, but it is fast enough and much more dev friendly. Will update in the next 24 hrs.

**Comment by wtheisen** [comment]
I tested these changes locally and they seem to work well so far! Just needs to be polished a little more so it's completely usable, awesome work!!

**Comment by ginglis13** [comment]
**Update**

Using different API for threadView as mentioned above. This API returns comment and post text as raw HTML, so I used a python lib called html2text to strip html elements from text. Updated requirements.txt accordingly. Everything should be working now, let me know of any issues! I can make a separate PR once this is complete to update readme.

**Comment by wtheisen** [comment]
Fantastic work

**Pull request merged**
